%YAML 1.2
---
- name: Update apt
  apt: update_cache=yes
  sudo: yes

- name: Install dependencies
  apt: pkg={{ item }}
  sudo: yes
  with_items:
    - build-essential
    - curl
    - git
    - libreadline-dev
    - libssl-dev
    - libyaml-dev
    - zlib1g-dev
    - libxml2-dev
    - libxslt1-dev
    - python-pycurl
    - make
    - cmake
    - pkg-config
    - tcl8.5
    - libcurl4-gnutls-dev
