%YAML 1.2
---
- name: Install ruby build
  git: repo=git://github.com/sstephenson/ruby-build.git
       dest=~/.rbenv/plugins/ruby-build

- name: Ensure fragments bash dir exists
  file: dest=~/.bash.d/ state=directory

- name: Copy exports file
  copy: src=ruby_build.bash
        dest=~/.bash.d/ruby_build.bash mode=700

- name: Source ruby build exports file
  lineinfile: dest=~/.bash_profile regexp="ruby_build" insertafter=EOF line="source ~/.bash.d/ruby_build.bash" create=yes state=present

- name: Install ruby
  shell: cd; bash -lc "CONFIGURE_OPTS=--disable-install-rdoc rbenv install {{ruby.version}}"
  when: ruby_is_installed.stdout != ruby.version
  notify: Sets global ruby version

- name: Sets global ruby version
  shell: cd; bash -lc "rbenv global {{ruby.version}}"

- name: Copy gemrc file tell rubygems not to install the documentation for each package locally
  copy: src=gemrc
        dest=~/.gemrc
